### PR TITLE
Added title and tooltip to local ranking

### PR DESCRIPTION
**Pull request by askiefer**
Addresses issue #72 

Lmk if you think this text sounds good or could use editing.

screen shot 2017-07-21 at 9 00 35 am

### CODE REVIEW

**Comment by askiefer** [comment]
Actually this isn't done yet - I see some UI issues on larger screen - so disregard for now

**Comment by thfield** [comment]
Re: Ammon's comment in the latest email thread:  I would expect #1 to be there best performing but the sort just goes numerically ascending according to whatever the building's property is. This gets done in the function `rankBuildings()`
We should probably change it so #1 is the"best"

**Comment by eayoungs** [comment]
I added a few changes related to *issue 57*. It's just a hack to update the reference for 2016, so it doesn't really close the issue but needs to be included for the current release.

**Comment by eayoungs** [comment]
Removed changes from this branch, will submit separate PR.

**Pull request closed without merging**
