### PR TITLE
81 estar score absent

### PR DESCRIPTION
**Pull request by thfield**
fixes ranking text in ring chart and hides text if there no energy star score reported.

screen shot 2017-08-05 at 12 08 49 pm

### CODE REVIEW

**Comment by thfield** [comment]
fixes #81

**Review by askiefer — COMMENTED** [review]
Tested with building apn=3752/011A and confirm that this omits the estar score if not present. I think we were changing this text from the EStar score paragraph to the local ranking paragraph (which should include a reference to EStar score I believe). So maybe in the instance of no Estar score the paragraph should read something along the lines of: ``There is no local ranking for this building. The national office median energy star score is 50.`` @thfield @eayoungs what do you think?

**Comment by thfield** [comment]
Agreed.  I believe there was another change to the wording in this spot that we're waiting on to get from Ammon?

**Comment by thfield** [comment]
if we end up abandoning this PR, make sure to cherry pick/pull in f7cc07b

**Comment by thfield** [comment]
closing to merge into `96-ring-chart`

**Pull request closed without merging**
