### PR TITLE
Added temporary (1 year) fix to issue 74

### PR DESCRIPTION
**Pull request by eayoungs**
This still needs to be revised before closing the issue but gives us a year to do so.

### CODE REVIEW

**Comment by thfield** [comment]
lgtm, just make sure **not** to close #74 yet

**Comment by thfield** [comment]
[fixed](https://github.com/sfbrigade/datasci-SF-Environment-Benchmark/pull/89/files#diff-5e5c014df471d720d257c5fd4368034fR417) with #89 i believe

**Comment by eayoungs** [comment]
Merging is blocked for me. Did you "approve" it?

**Review by thfield — APPROVED** [review]

**Comment by thfield** [comment]
closing for now, as i believe this is no longer necessary

**Pull request closed without merging**
