### PR TITLE
dashed highlight with label

### PR DESCRIPTION
**Pull request by thfield**
addresses part of #55
screen shot 2017-07-12 at 2 20 48 pm

### CODE REVIEW

**Comment by thfield** [comment]
screen shot 2017-07-12 at 2 36 05 pm
uppercase the label to look more like mockup

**Comment by thfield** [comment]
need to rename `histogramHighlight()` to `addHighlightLine()` and use for both histogram and quartile chart -- it is the same function.

**Comment by thfield** [comment]
screen shot 2017-07-13 at 2 26 23 pm
align highlight line, use '.axislabel' class for axis labels instead of '.label': since these are svg text elements, the property to change color is "fill" instead of "color"

**Comment by askiefer** [comment]
This looks good to me @thfield, I merged with master and added back the blue for the highlight color (I must have changed it to lightgray in the previous PR for some reason..)

**Comment by thfield** [comment]
(i think you changed it to match juliana's wireframes)

**Pull request merged**
